export const keywords = [
  'makemytrip',
  'paytm',
  'zomato',
  'myntra',
  'ola',
  'bookmyshow',
  'rebel foods',
  'unacademy',
  'boat',
  'dominos',
  'lazypay',
  'postpe',
  '26°',
  'faasos',
  'blinkit',
  'grofers',
  'zeptoconsumerapp',
  'upstox',
  'amazon',
  'flipkart',
];
export const unwantedCompanies = [
  'google',
  'googlequicksearchbox',
  'gm',
  'powersaver',
  'com',
  'android',
  'apps',
  'messaging',
  'application',
  'done',
  'bt',
  'in',
  'mShop',
  'shopping',
  'vending',
  'customerapp',
  'done',
  'capp',
  'providers',
  'downloads',
  'xyz',
  'app',
  'local',
  'uapp',
  'deskclock',
  'videoplayer',
  'add',
  'southasia',
  'lotusintouch',
  'bt',
];
// Regular expression to detect unwanted details
export const unwantedDetailsRegex =
  /(otp|transaction|payment|account|statement|balance|credited|debited|purchase|order|code|verification|charged|password|pin|ssn|dob|credit card|cvv|expiry|address|security|id|personal|confidential|secret|passport|license|security code|secret code|private|consumed|validity|fund|debit|credit|fund|balance|cdsl|investor|hotspot|messages is doing work in the background|usb debugging connected|tethering or hotspot active|1 device(s) connected|no devices connected|incoming|spam|blocked|call|salary|screenshot|alert|battery|draining|message|background|battery|hotspot|device)/i;

export const unwantedApps = /(whats|contacts|Wi-Fi|smsandnotifications)/i;
